### PR TITLE
improvers + fixed bugs + added ban time when no more attempts left

### PR DESCRIPTION
**Pull request by oussamamadjmaa**
- Fixed some bugs on migration and user model
- added ban time after no more attempts left
- improves on VerifyMobileController.php
- and other more small improves

### CODE REVIEW

**Comment by PovilasKorop** [comment]
@oussamamadjmaa so many changes... To be honest, I didn't have any plans to expand this repository and maintain it for the future, it was just a demo project for the video.

Could you maybe fork this repository and then make updates to that as your own repository?

I appreciate the contribution, but I just don't have time to review and maintain the changes. This project could have a dozen more features, but I didn't plan that, I'm focused on other content.

**Comment by oussamamadjmaa** [comment]
Thanks for responding, but there's so many changes , most of theme r fix for bugs , and problems on last update , which u can notice them if u clone the repo and try it again, i added ban time, bcz i think he didn't know how to deal with attempts.

And  last 3 pushes was commited by mistake , it doesn't contain any updates , the updates is only on first commit , u can see the 8 changed files,

However, thank u so much for ur time.

**Comment by PovilasKorop** [comment]
@oussamamadjmaa yes I saw those 8 changed files, and that's exactly what I don't have time for, there are a lot of things that are debatable (like, you deleted a few lines from RegisterController?), so I need to comment on them, then you fix something, then I need to re-test, so that thing takes time, which I currently don't have.

So I think I will stop here and won't review/merge, unless more people ask me to "officially" provide long-term for this demo repository, which I didn't plan.

**Comment by oussamamadjmaa** [comment]
No problem , i understand u, i won't do all that changes for no reason, i decided after i saw many errors after last merge, but i want u to notice some small things, so this repository stay clean and can be tested from other people who want to learn from it :

aaa and small clarifation before we go , i removed that few lines on register bcz i passed true to `sendMobileVerificationNotification` method on the event file, which will fill that data just when it's needed.

and here's reason why i did that update,

-  he forgot to change `mobile_last_send` column name to `mobile_verify_code_sent_at` on model after he changed it on controller and on migration.
- config file i added this `?:` like `env('MOBILE_MAX_ATTEMPTS', 3)?:3,` to avoid env setting value as `empty string ""` like what happened to me, which will cause error when filling `mobile_attempts_left` column on database.
- `mobile_verify_code_sent_at` timestamp doesn't have default value like nullable , which will cause errors when u run migration.
- `MustVerifyMobile` has forceFill without `->save();`
- `VerifyMobileController.php` (there's no need to use `Carbon::parse` or `Carbon::now()`) and i think dealing with waiting error isn't correct , for that i added in place of that ban time, which will make it more clear.

and i'm really sorry for ur time. have great day brother [PovilasKorop](https://github.com/PovilasKorop) and which u all the best.

**Comment by PovilasKorop** [comment]
@oussamamadjmaa ok fine, you convinced me - since you worked on this quite thoroughly and thought things through, I will merge your PR.

By the way @MaxRomagnoli please read the comments above on improvements.

**Comment by oussamamadjmaa** [comment]
@PovilasKorop thank u so much, i appreciate that.

**Pull request merged**
